"""Fix: ensure student_id is String and class_id added

Revision ID: 7cb69e8cb353
Revises: c7036131fcd8
Create Date: 2025-05-15 16:59:29.309084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cb69e8cb353'
down_revision = 'c7036131fcd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classroom',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('raw_student_data', schema=None) as batch_op:
        batch_op.drop_column('id')

    with op.batch_alter_table('transformed_student_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_id', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint(None, ['student_id'])
        batch_op.create_foreign_key(None, 'classroom', ['class_id'], ['id'])
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transformed_student_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('class_id')

    with op.batch_alter_table('raw_student_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))

    op.drop_table('classroom')
    # ### end Alembic commands ###
