"""Initial migration

Revision ID: c7036131fcd8
Revises: 
Create Date: 2025-05-15 16:46:43.753139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7036131fcd8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classroom',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('raw_student_data', schema=None) as batch_op:
        # batch_op.alter_column('student_id',
        #        existing_type=sa.VARCHAR(length=50),
        #        type_=sa.Integer(),
        #        existing_nullable=False,
        #        autoincrement=True)
        batch_op.drop_column('id')

    with op.batch_alter_table('transformed_student_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_id', sa.String(length=20), nullable=True))
        batch_op.alter_column('student_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.create_unique_constraint(None, ['student_id'])
        batch_op.create_foreign_key(None, 'classroom', ['class_id'], ['id'])
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transformed_student_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('student_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('class_id')

    with op.batch_alter_table('raw_student_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.alter_column('student_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               autoincrement=True)

    op.drop_table('classroom')
    # ### end Alembic commands ###
